//! Events: the [`Event`] trait (with its [`Identifier`]/[`Specifier`]/[`Tags`]
//! components) and the [`Events`] buffer.
//!
//! An event is a plain struct carrying `#[revisioned(revision = N)]` (for
//! payload (de)serialisation) and `#[derive(Event)]` with an `#[event(..)]`
//! attribute that declares its `identifier` and its `tags`:
//!
//! ```
//! use eventric_domain::event::{
//!     Event,
//!     Identifier as _,
//! };
//! use revision::revisioned;
//!
//! #[revisioned(revision = 1)]
//! #[derive(Event)]
//! #[event(
//!     identifier: account_opened,
//!     tags: { account: id }
//! )]
//! struct AccountOpened {
//!     id: String,
//! }
//!
//! // `identifier()` returns the name as written; the stream indexes the event
//! // under its hash (`Identifier::type_name`).
//! assert_eq!(AccountOpened::identifier(), "account_opened");
//! ```
//!
//! See the [`Event`](macro@crate::event::Event) derive for the full
//! `#[event(..)]` grammar and the tag-value forms (bare ident, `&this.expr`,
//! closure, and `[list]` values for several tags under one prefix).

use std::collections::BTreeSet;

use error_stack::{
    Report,
    ResultExt as _,
};
pub use eventric_macros::Event;
use eventric_stream::{
    event::{
        Data,
        Event as StreamEvent,
        Facets,
        Name,
        Tag,
        Type,
        Version,
    },
    stream::operate::select::TypeSelector,
};
use fancy_constructor::new;
use revision::{
    DeserializeRevisioned,
    SerializeRevisioned,
};

use crate::error::Error;

// =================================================================================================
// Event
// =================================================================================================

// Event

/// A domain event: a `revision`-(de)serialisable payload with a stable
/// [`Identifier`] and queryable [`Tags`]. The unit a projection folds and an
/// action appends; derived by `#[derive(Event)]`.
pub trait Event: DeserializeRevisioned + Identifier + Tags + SerializeRevisioned {}

// Identifier

/// An event type's stable name — a `&'static str` literal, plus the hashed
/// [`Name`] the stream indexes it under.
pub trait Identifier {
    /// The event type's name, as a validated literal.
    fn identifier() -> &'static str;

    /// The event type's name hashed the same way the stream indexes it, used to
    /// recognise an event by type.
    fn type_name() -> Result<Name<u64>, Report<Error>> {
        Name::new(Self::identifier())
            .change_context(Error)
            .map(Into::into)
    }
}

// Specifier

/// Builds the [`TypeSelector`] that selects this event type.
/// Blanket-implemented for any [`Identifier`].
pub trait Specifier {
    /// The type-selector matching this event type (across all versions).
    fn specifier() -> Result<TypeSelector<String>, Report<Error>>;
}

impl<T> Specifier for T
where
    T: Identifier,
{
    fn specifier() -> Result<TypeSelector<String>, Report<Error>> {
        TypeSelector::new(T::identifier()).change_context(Error)
    }
}

// Tags

/// An event's queryable [`Tag`]s, derived from its payload — generated by
/// `#[derive(Event)]` from the `#[event(.., tags: { <prefix>: <value>, .. })]`
/// attribute.
pub trait Tags {
    /// Build this event's tags (validated here; hashed later, at append).
    fn tags(&self) -> Result<Vec<Tag<String>>, Report<Error>>;
}

// -------------------------------------------------------------------------------------------------

// Events

/// A buffer of candidate events an [`Act`](crate::action::Act) stages for
/// append.
#[derive(new, Debug)]
pub struct Events {
    #[new(default)]
    events: Vec<StreamEvent<(), String>>,
}

impl Events {
    /// Stage `event` for append: serialise its payload (via `revision`), source
    /// its stream `Version` from the revision number, and derive its facets.
    pub fn append<E>(&mut self, event: &E) -> Result<(), Report<Error>>
    where
        E: Event,
    {
        let data = revision::to_vec(event)
            .change_context(Error)
            .attach("events/append/revision")?;
        let data = Data::new(data).change_context(Error)?;

        let name = Name::new(E::identifier()).change_context(Error)?;
        // The event's stream `Version` is sourced directly from the `revision`
        // schema number, so the two cannot diverge (there is no separate version
        // to declare or forget to bump). `revision` is a `u16`; `Version` is a
        // `u8` — 256+ revisions of one event type is implausible, but it errors
        // rather than truncating silently.
        let version = u8::try_from(E::revision())
            .change_context(Error)
            .attach("events/append/version: revision exceeds u8::MAX")?;
        let ty = Type::new(name, Version::new(version));
        let tags = event.tags()?.into_iter().collect::<BTreeSet<_>>();

        self.events
            .push(StreamEvent::new(data, Facets::new(ty, tags), ()));

        Ok(())
    }

    /// Consume the buffer, yielding the staged candidate events.
    #[must_use]
    pub fn take(self) -> Vec<StreamEvent<(), String>> {
        self.events
    }
}
